# Generated by Django 3.1 on 2020-08-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20200826_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
